#pragma once

#define VEC_SWIZZLE_VEC2_PROP(A, B) \
public Vector2 A##B \
{ \
    get \
    { \
        return new Vector2(A, B); \
    } \
    set \
    { \
        A = value.X; \
        B = value.Y; \
    } \
} 
#define VEC_SWIZZLE_VEC3_PROP(A, B, C) \
public Vector3 A##B##C \
{ \
    get \
    { \
        return new Vector3(A, B, C); \
    } \
    set \
    { \
        A = value.X; \
        B = value.Y; \
        C = value.Z; \
    } \
}
#define VEC_SWIZZLE_VEC4_PROP(A, B, C, D) \
public Vector4 A##B##C##D \
{ \
    get \
    { \
        return new Vector4(A, B, C, D); \
    } \
    set \
    { \
        A = value.X; \
        B = value.Y; \
        C = value.Z; \
        D = value.W; \
    } \
}

#define VEC_SWIZZLE_VEC2_FROM_VEC2(A, B) \
    VEC_SWIZZLE_VEC2_PROP(A, A) \
    VEC_SWIZZLE_VEC2_PROP(A, B) \
    VEC_SWIZZLE_VEC2_PROP(B, A) \
    VEC_SWIZZLE_VEC2_PROP(B, B) \

#define VEC_SWIZZLE_VEC3_FROM_VEC2(A, B) \
    VEC_SWIZZLE_VEC3_PROP(A, A, A) \
    VEC_SWIZZLE_VEC3_PROP(A, A, B) \
    VEC_SWIZZLE_VEC3_PROP(A, B, A) \
    VEC_SWIZZLE_VEC3_PROP(A, B, B) \
    VEC_SWIZZLE_VEC3_PROP(B, A, A) \
    VEC_SWIZZLE_VEC3_PROP(B, A, B) \
    VEC_SWIZZLE_VEC3_PROP(B, B, A) \
    VEC_SWIZZLE_VEC3_PROP(B, B, B) \

#define VEC_SWIZZLE_VEC4_FROM_VEC2(A, B) \
    VEC_SWIZZLE_VEC4_PROP(A, A, A, A) \
    VEC_SWIZZLE_VEC4_PROP(A, A, A, B) \
    VEC_SWIZZLE_VEC4_PROP(A, A, B, A) \
    VEC_SWIZZLE_VEC4_PROP(A, A, B, B) \
    VEC_SWIZZLE_VEC4_PROP(A, B, A, A) \
    VEC_SWIZZLE_VEC4_PROP(A, B, A, B) \
    VEC_SWIZZLE_VEC4_PROP(A, B, B, A) \
    VEC_SWIZZLE_VEC4_PROP(A, B, B, B) \
    VEC_SWIZZLE_VEC4_PROP(B, A, A, A) \
    VEC_SWIZZLE_VEC4_PROP(B, A, A, B) \
    VEC_SWIZZLE_VEC4_PROP(B, A, B, A) \
    VEC_SWIZZLE_VEC4_PROP(B, A, B, B) \
    VEC_SWIZZLE_VEC4_PROP(B, B, A, A) \
    VEC_SWIZZLE_VEC4_PROP(B, B, A, B) \
    VEC_SWIZZLE_VEC4_PROP(B, B, B, A) \
    VEC_SWIZZLE_VEC4_PROP(B, B, B, B) \

#define VEC_SWIZZLE_VEC2_FULL_VEC2 \
    VEC_SWIZZLE_VEC2_FROM_VEC2(X, Y) \
    VEC_SWIZZLE_VEC2_FROM_VEC2(U, V) \

#define VEC_SWIZZLE_VEC2_FULL_VEC3 \
    VEC_SWIZZLE_VEC3_FROM_VEC2(X, Y) \
    VEC_SWIZZLE_VEC3_FROM_VEC2(U, V) \

#define VEC_SWIZZLE_VEC2_FULL_VEC4 \
    VEC_SWIZZLE_VEC4_FROM_VEC2(X, Y) \
    VEC_SWIZZLE_VEC4_FROM_VEC2(U, V) \

#define VEC_SWIZZLE_VEC2_FROM_VEC3(A, B, C) \
    VEC_SWIZZLE_VEC2_PROP(A, A) \
    VEC_SWIZZLE_VEC2_PROP(A, B) \
    VEC_SWIZZLE_VEC2_PROP(A, C) \
    VEC_SWIZZLE_VEC2_PROP(B, A) \
    VEC_SWIZZLE_VEC2_PROP(B, B) \
    VEC_SWIZZLE_VEC2_PROP(B, C) \
    VEC_SWIZZLE_VEC2_PROP(C, A) \
    VEC_SWIZZLE_VEC2_PROP(C, B) \
    VEC_SWIZZLE_VEC2_PROP(C, C) \

#define VEC_SWIZZLE_VEC3_FROM_VEC3(A, B, C) \
    VEC_SWIZZLE_VEC3_PROP(A, A, A) \
    VEC_SWIZZLE_VEC3_PROP(A, A, B) \
    VEC_SWIZZLE_VEC3_PROP(A, A, C) \
    VEC_SWIZZLE_VEC3_PROP(A, B, A) \
    VEC_SWIZZLE_VEC3_PROP(A, B, B) \
    VEC_SWIZZLE_VEC3_PROP(A, B, C) \
    VEC_SWIZZLE_VEC3_PROP(A, C, A) \
    VEC_SWIZZLE_VEC3_PROP(A, C, B) \
    VEC_SWIZZLE_VEC3_PROP(A, C, C) \
    VEC_SWIZZLE_VEC3_PROP(B, A, A) \
    VEC_SWIZZLE_VEC3_PROP(B, A, B) \
    VEC_SWIZZLE_VEC3_PROP(B, A, C) \
    VEC_SWIZZLE_VEC3_PROP(B, B, A) \
    VEC_SWIZZLE_VEC3_PROP(B, B, B) \
    VEC_SWIZZLE_VEC3_PROP(B, B, C) \
    VEC_SWIZZLE_VEC3_PROP(B, C, A) \
    VEC_SWIZZLE_VEC3_PROP(B, C, B) \
    VEC_SWIZZLE_VEC3_PROP(B, C, C) \
    VEC_SWIZZLE_VEC3_PROP(C, A, A) \
    VEC_SWIZZLE_VEC3_PROP(C, A, B) \
    VEC_SWIZZLE_VEC3_PROP(C, A, C) \
    VEC_SWIZZLE_VEC3_PROP(C, B, A) \
    VEC_SWIZZLE_VEC3_PROP(C, B, B) \
    VEC_SWIZZLE_VEC3_PROP(C, B, C) \
    VEC_SWIZZLE_VEC3_PROP(C, C, A) \
    VEC_SWIZZLE_VEC3_PROP(C, C, B) \
    VEC_SWIZZLE_VEC3_PROP(C, C, C) \

#define VEC_SWIZZLE_VEC4_FROM_VEC3(A, B, C) \
    VEC_SWIZZLE_VEC4_PROP(A, A, A, A) \
    VEC_SWIZZLE_VEC4_PROP(A, A, A, B) \
    VEC_SWIZZLE_VEC4_PROP(A, A, A, C) \
    VEC_SWIZZLE_VEC4_PROP(A, A, B, A) \
    VEC_SWIZZLE_VEC4_PROP(A, A, B, B) \
    VEC_SWIZZLE_VEC4_PROP(A, A, B, C) \
    VEC_SWIZZLE_VEC4_PROP(A, A, C, A) \
    VEC_SWIZZLE_VEC4_PROP(A, A, C, B) \
    VEC_SWIZZLE_VEC4_PROP(A, A, C, C) \
    VEC_SWIZZLE_VEC4_PROP(A, B, A, A) \
    VEC_SWIZZLE_VEC4_PROP(A, B, A, B) \
    VEC_SWIZZLE_VEC4_PROP(A, B, A, C) \
    VEC_SWIZZLE_VEC4_PROP(A, B, B, A) \
    VEC_SWIZZLE_VEC4_PROP(A, B, B, B) \
    VEC_SWIZZLE_VEC4_PROP(A, B, B, C) \
    VEC_SWIZZLE_VEC4_PROP(A, B, C, A) \
    VEC_SWIZZLE_VEC4_PROP(A, B, C, B) \
    VEC_SWIZZLE_VEC4_PROP(A, B, C, C) \
    VEC_SWIZZLE_VEC4_PROP(A, C, A, A) \
    VEC_SWIZZLE_VEC4_PROP(A, C, A, B) \
    VEC_SWIZZLE_VEC4_PROP(A, C, A, C) \
    VEC_SWIZZLE_VEC4_PROP(A, C, B, A) \
    VEC_SWIZZLE_VEC4_PROP(A, C, B, B) \
    VEC_SWIZZLE_VEC4_PROP(A, C, B, C) \
    VEC_SWIZZLE_VEC4_PROP(A, C, C, A) \
    VEC_SWIZZLE_VEC4_PROP(A, C, C, B) \
    VEC_SWIZZLE_VEC4_PROP(A, C, C, C) \
    VEC_SWIZZLE_VEC4_PROP(B, A, A, A) \
    VEC_SWIZZLE_VEC4_PROP(B, A, A, B) \
    VEC_SWIZZLE_VEC4_PROP(B, A, A, C) \
    VEC_SWIZZLE_VEC4_PROP(B, A, B, A) \
    VEC_SWIZZLE_VEC4_PROP(B, A, B, B) \
    VEC_SWIZZLE_VEC4_PROP(B, A, B, C) \
    VEC_SWIZZLE_VEC4_PROP(B, A, C, A) \
    VEC_SWIZZLE_VEC4_PROP(B, A, C, B) \
    VEC_SWIZZLE_VEC4_PROP(B, A, C, C) \
    VEC_SWIZZLE_VEC4_PROP(B, B, A, A) \
    VEC_SWIZZLE_VEC4_PROP(B, B, A, B) \
    VEC_SWIZZLE_VEC4_PROP(B, B, A, C) \
    VEC_SWIZZLE_VEC4_PROP(B, B, B, A) \
    VEC_SWIZZLE_VEC4_PROP(B, B, B, B) \
    VEC_SWIZZLE_VEC4_PROP(B, B, B, C) \
    VEC_SWIZZLE_VEC4_PROP(B, B, C, A) \
    VEC_SWIZZLE_VEC4_PROP(B, B, C, B) \
    VEC_SWIZZLE_VEC4_PROP(B, B, C, C) \
    VEC_SWIZZLE_VEC4_PROP(B, C, A, A) \
    VEC_SWIZZLE_VEC4_PROP(B, C, A, B) \
    VEC_SWIZZLE_VEC4_PROP(B, C, A, C) \
    VEC_SWIZZLE_VEC4_PROP(B, C, B, A) \
    VEC_SWIZZLE_VEC4_PROP(B, C, B, B) \
    VEC_SWIZZLE_VEC4_PROP(B, C, B, C) \
    VEC_SWIZZLE_VEC4_PROP(B, C, C, A) \
    VEC_SWIZZLE_VEC4_PROP(B, C, C, B) \
    VEC_SWIZZLE_VEC4_PROP(B, C, C, C) \
    VEC_SWIZZLE_VEC4_PROP(C, A, A, A) \
    VEC_SWIZZLE_VEC4_PROP(C, A, A, B) \
    VEC_SWIZZLE_VEC4_PROP(C, A, A, C) \
    VEC_SWIZZLE_VEC4_PROP(C, A, B, A) \
    VEC_SWIZZLE_VEC4_PROP(C, A, B, B) \
    VEC_SWIZZLE_VEC4_PROP(C, A, B, C) \
    VEC_SWIZZLE_VEC4_PROP(C, A, C, A) \
    VEC_SWIZZLE_VEC4_PROP(C, A, C, B) \
    VEC_SWIZZLE_VEC4_PROP(C, A, C, C) \
    VEC_SWIZZLE_VEC4_PROP(C, B, A, A) \
    VEC_SWIZZLE_VEC4_PROP(C, B, A, B) \
    VEC_SWIZZLE_VEC4_PROP(C, B, A, C) \
    VEC_SWIZZLE_VEC4_PROP(C, B, B, A) \
    VEC_SWIZZLE_VEC4_PROP(C, B, B, B) \
    VEC_SWIZZLE_VEC4_PROP(C, B, B, C) \
    VEC_SWIZZLE_VEC4_PROP(C, B, C, A) \
    VEC_SWIZZLE_VEC4_PROP(C, B, C, B) \
    VEC_SWIZZLE_VEC4_PROP(C, B, C, C) \
    VEC_SWIZZLE_VEC4_PROP(C, C, A, A) \
    VEC_SWIZZLE_VEC4_PROP(C, C, A, B) \
    VEC_SWIZZLE_VEC4_PROP(C, C, A, C) \
    VEC_SWIZZLE_VEC4_PROP(C, C, B, A) \
    VEC_SWIZZLE_VEC4_PROP(C, C, B, B) \
    VEC_SWIZZLE_VEC4_PROP(C, C, B, C) \
    VEC_SWIZZLE_VEC4_PROP(C, C, C, A) \
    VEC_SWIZZLE_VEC4_PROP(C, C, C, B) \
    VEC_SWIZZLE_VEC4_PROP(C, C, C, C) \

#define VEC_SWIZZLE_VEC3_FULL_VEC2 \
    VEC_SWIZZLE_VEC2_FROM_VEC3(X, Y, Z) \
    VEC_SWIZZLE_VEC2_FROM_VEC3(R, G, B) \
    VEC_SWIZZLE_VEC2_FROM_VEC3(U, V, W) \

#define VEC_SWIZZLE_VEC3_FULL_VEC3 \
    VEC_SWIZZLE_VEC3_FROM_VEC3(X, Y, Z) \
    VEC_SWIZZLE_VEC3_FROM_VEC3(R, G, B) \
    VEC_SWIZZLE_VEC3_FROM_VEC3(U, V, W) \

#define VEC_SWIZZLE_VEC3_FULL_VEC4 \
    VEC_SWIZZLE_VEC4_FROM_VEC3(X, Y, Z) \
    VEC_SWIZZLE_VEC4_FROM_VEC3(R, G, B) \
    VEC_SWIZZLE_VEC4_FROM_VEC3(U, V, W) \

#define VEC_SWIZZLE_VEC2_FROM_VEC4(A, B, C, D) \
    VEC_SWIZZLE_VEC2_PROP(A, A) \
    VEC_SWIZZLE_VEC2_PROP(A, B) \
    VEC_SWIZZLE_VEC2_PROP(A, C) \
    VEC_SWIZZLE_VEC2_PROP(A, D) \
    VEC_SWIZZLE_VEC2_PROP(B, A) \
    VEC_SWIZZLE_VEC2_PROP(B, B) \
    VEC_SWIZZLE_VEC2_PROP(B, C) \
    VEC_SWIZZLE_VEC2_PROP(B, D) \
    VEC_SWIZZLE_VEC2_PROP(C, A) \
    VEC_SWIZZLE_VEC2_PROP(C, B) \
    VEC_SWIZZLE_VEC2_PROP(C, C) \
    VEC_SWIZZLE_VEC2_PROP(C, D) \
    VEC_SWIZZLE_VEC2_PROP(D, A) \
    VEC_SWIZZLE_VEC2_PROP(D, B) \
    VEC_SWIZZLE_VEC2_PROP(D, C) \
    VEC_SWIZZLE_VEC2_PROP(D, D) \

#define VEC_SWIZZLE_VEC3_FROM_VEC4(A, B, C, D) \
    VEC_SWIZZLE_VEC3_PROP(A, A, A) \
    VEC_SWIZZLE_VEC3_PROP(A, A, B) \
    VEC_SWIZZLE_VEC3_PROP(A, A, C) \
    VEC_SWIZZLE_VEC3_PROP(A, A, D) \
    VEC_SWIZZLE_VEC3_PROP(A, B, A) \
    VEC_SWIZZLE_VEC3_PROP(A, B, B) \
    VEC_SWIZZLE_VEC3_PROP(A, B, C) \
    VEC_SWIZZLE_VEC3_PROP(A, B, D) \
    VEC_SWIZZLE_VEC3_PROP(A, C, A) \
    VEC_SWIZZLE_VEC3_PROP(A, C, B) \
    VEC_SWIZZLE_VEC3_PROP(A, C, C) \
    VEC_SWIZZLE_VEC3_PROP(A, C, D) \
    VEC_SWIZZLE_VEC3_PROP(A, D, A) \
    VEC_SWIZZLE_VEC3_PROP(A, D, B) \
    VEC_SWIZZLE_VEC3_PROP(A, D, C) \
    VEC_SWIZZLE_VEC3_PROP(A, D, D) \
    VEC_SWIZZLE_VEC3_PROP(B, A, A) \
    VEC_SWIZZLE_VEC3_PROP(B, A, B) \
    VEC_SWIZZLE_VEC3_PROP(B, A, C) \
    VEC_SWIZZLE_VEC3_PROP(B, A, D) \
    VEC_SWIZZLE_VEC3_PROP(B, B, A) \
    VEC_SWIZZLE_VEC3_PROP(B, B, B) \
    VEC_SWIZZLE_VEC3_PROP(B, B, C) \
    VEC_SWIZZLE_VEC3_PROP(B, B, D) \
    VEC_SWIZZLE_VEC3_PROP(B, C, A) \
    VEC_SWIZZLE_VEC3_PROP(B, C, B) \
    VEC_SWIZZLE_VEC3_PROP(B, C, C) \
    VEC_SWIZZLE_VEC3_PROP(B, C, D) \
    VEC_SWIZZLE_VEC3_PROP(B, D, A) \
    VEC_SWIZZLE_VEC3_PROP(B, D, B) \
    VEC_SWIZZLE_VEC3_PROP(B, D, C) \
    VEC_SWIZZLE_VEC3_PROP(B, D, D) \
    VEC_SWIZZLE_VEC3_PROP(C, A, A) \
    VEC_SWIZZLE_VEC3_PROP(C, A, B) \
    VEC_SWIZZLE_VEC3_PROP(C, A, C) \
    VEC_SWIZZLE_VEC3_PROP(C, A, D) \
    VEC_SWIZZLE_VEC3_PROP(C, B, A) \
    VEC_SWIZZLE_VEC3_PROP(C, B, B) \
    VEC_SWIZZLE_VEC3_PROP(C, B, C) \
    VEC_SWIZZLE_VEC3_PROP(C, B, D) \
    VEC_SWIZZLE_VEC3_PROP(C, C, A) \
    VEC_SWIZZLE_VEC3_PROP(C, C, B) \
    VEC_SWIZZLE_VEC3_PROP(C, C, C) \
    VEC_SWIZZLE_VEC3_PROP(C, C, D) \
    VEC_SWIZZLE_VEC3_PROP(C, D, A) \
    VEC_SWIZZLE_VEC3_PROP(C, D, B) \
    VEC_SWIZZLE_VEC3_PROP(C, D, C) \
    VEC_SWIZZLE_VEC3_PROP(C, D, D) \
    VEC_SWIZZLE_VEC3_PROP(D, A, A) \
    VEC_SWIZZLE_VEC3_PROP(D, A, B) \
    VEC_SWIZZLE_VEC3_PROP(D, A, C) \
    VEC_SWIZZLE_VEC3_PROP(D, A, D) \
    VEC_SWIZZLE_VEC3_PROP(D, B, A) \
    VEC_SWIZZLE_VEC3_PROP(D, B, B) \
    VEC_SWIZZLE_VEC3_PROP(D, B, C) \
    VEC_SWIZZLE_VEC3_PROP(D, B, D) \
    VEC_SWIZZLE_VEC3_PROP(D, C, A) \
    VEC_SWIZZLE_VEC3_PROP(D, C, B) \
    VEC_SWIZZLE_VEC3_PROP(D, C, C) \
    VEC_SWIZZLE_VEC3_PROP(D, C, D) \
    VEC_SWIZZLE_VEC3_PROP(D, D, A) \
    VEC_SWIZZLE_VEC3_PROP(D, D, B) \
    VEC_SWIZZLE_VEC3_PROP(D, D, C) \
    VEC_SWIZZLE_VEC3_PROP(D, D, D) \

#define VEC_SWIZZLE_VEC4_FROM_VEC4(A, B, C, D) \
    VEC_SWIZZLE_VEC4_PROP(A, A, A, A) \
    VEC_SWIZZLE_VEC4_PROP(A, A, A, B) \
    VEC_SWIZZLE_VEC4_PROP(A, A, A, C) \
    VEC_SWIZZLE_VEC4_PROP(A, A, A, D) \
    VEC_SWIZZLE_VEC4_PROP(A, A, B, A) \
    VEC_SWIZZLE_VEC4_PROP(A, A, B, B) \
    VEC_SWIZZLE_VEC4_PROP(A, A, B, C) \
    VEC_SWIZZLE_VEC4_PROP(A, A, B, D) \
    VEC_SWIZZLE_VEC4_PROP(A, A, C, A) \
    VEC_SWIZZLE_VEC4_PROP(A, A, C, B) \
    VEC_SWIZZLE_VEC4_PROP(A, A, C, C) \
    VEC_SWIZZLE_VEC4_PROP(A, A, C, D) \
    VEC_SWIZZLE_VEC4_PROP(A, A, D, A) \
    VEC_SWIZZLE_VEC4_PROP(A, A, D, B) \
    VEC_SWIZZLE_VEC4_PROP(A, A, D, C) \
    VEC_SWIZZLE_VEC4_PROP(A, A, D, D) \
    VEC_SWIZZLE_VEC4_PROP(A, B, A, A) \
    VEC_SWIZZLE_VEC4_PROP(A, B, A, B) \
    VEC_SWIZZLE_VEC4_PROP(A, B, A, C) \
    VEC_SWIZZLE_VEC4_PROP(A, B, A, D) \
    VEC_SWIZZLE_VEC4_PROP(A, B, B, A) \
    VEC_SWIZZLE_VEC4_PROP(A, B, B, B) \
    VEC_SWIZZLE_VEC4_PROP(A, B, B, C) \
    VEC_SWIZZLE_VEC4_PROP(A, B, B, D) \
    VEC_SWIZZLE_VEC4_PROP(A, B, C, A) \
    VEC_SWIZZLE_VEC4_PROP(A, B, C, B) \
    VEC_SWIZZLE_VEC4_PROP(A, B, C, C) \
    VEC_SWIZZLE_VEC4_PROP(A, B, C, D) \
    VEC_SWIZZLE_VEC4_PROP(A, B, D, A) \
    VEC_SWIZZLE_VEC4_PROP(A, B, D, B) \
    VEC_SWIZZLE_VEC4_PROP(A, B, D, C) \
    VEC_SWIZZLE_VEC4_PROP(A, B, D, D) \
    VEC_SWIZZLE_VEC4_PROP(A, C, A, A) \
    VEC_SWIZZLE_VEC4_PROP(A, C, A, B) \
    VEC_SWIZZLE_VEC4_PROP(A, C, A, C) \
    VEC_SWIZZLE_VEC4_PROP(A, C, A, D) \
    VEC_SWIZZLE_VEC4_PROP(A, C, B, A) \
    VEC_SWIZZLE_VEC4_PROP(A, C, B, B) \
    VEC_SWIZZLE_VEC4_PROP(A, C, B, C) \
    VEC_SWIZZLE_VEC4_PROP(A, C, B, D) \
    VEC_SWIZZLE_VEC4_PROP(A, C, C, A) \
    VEC_SWIZZLE_VEC4_PROP(A, C, C, B) \
    VEC_SWIZZLE_VEC4_PROP(A, C, C, C) \
    VEC_SWIZZLE_VEC4_PROP(A, C, C, D) \
    VEC_SWIZZLE_VEC4_PROP(A, C, D, A) \
    VEC_SWIZZLE_VEC4_PROP(A, C, D, B) \
    VEC_SWIZZLE_VEC4_PROP(A, C, D, C) \
    VEC_SWIZZLE_VEC4_PROP(A, C, D, D) \
    VEC_SWIZZLE_VEC4_PROP(A, D, A, A) \
    VEC_SWIZZLE_VEC4_PROP(A, D, A, B) \
    VEC_SWIZZLE_VEC4_PROP(A, D, A, C) \
    VEC_SWIZZLE_VEC4_PROP(A, D, A, D) \
    VEC_SWIZZLE_VEC4_PROP(A, D, B, A) \
    VEC_SWIZZLE_VEC4_PROP(A, D, B, B) \
    VEC_SWIZZLE_VEC4_PROP(A, D, B, C) \
    VEC_SWIZZLE_VEC4_PROP(A, D, B, D) \
    VEC_SWIZZLE_VEC4_PROP(A, D, C, A) \
    VEC_SWIZZLE_VEC4_PROP(A, D, C, B) \
    VEC_SWIZZLE_VEC4_PROP(A, D, C, C) \
    VEC_SWIZZLE_VEC4_PROP(A, D, C, D) \
    VEC_SWIZZLE_VEC4_PROP(A, D, D, A) \
    VEC_SWIZZLE_VEC4_PROP(A, D, D, B) \
    VEC_SWIZZLE_VEC4_PROP(A, D, D, C) \
    VEC_SWIZZLE_VEC4_PROP(A, D, D, D) \
    \
    VEC_SWIZZLE_VEC4_PROP(B, A, A, A) \
    VEC_SWIZZLE_VEC4_PROP(B, A, A, B) \
    VEC_SWIZZLE_VEC4_PROP(B, A, A, C) \
    VEC_SWIZZLE_VEC4_PROP(B, A, A, D) \
    VEC_SWIZZLE_VEC4_PROP(B, A, B, A) \
    VEC_SWIZZLE_VEC4_PROP(B, A, B, B) \
    VEC_SWIZZLE_VEC4_PROP(B, A, B, C) \
    VEC_SWIZZLE_VEC4_PROP(B, A, B, D) \
    VEC_SWIZZLE_VEC4_PROP(B, A, C, A) \
    VEC_SWIZZLE_VEC4_PROP(B, A, C, B) \
    VEC_SWIZZLE_VEC4_PROP(B, A, C, C) \
    VEC_SWIZZLE_VEC4_PROP(B, A, C, D) \
    VEC_SWIZZLE_VEC4_PROP(B, A, D, A) \
    VEC_SWIZZLE_VEC4_PROP(B, A, D, B) \
    VEC_SWIZZLE_VEC4_PROP(B, A, D, C) \
    VEC_SWIZZLE_VEC4_PROP(B, A, D, D) \
    VEC_SWIZZLE_VEC4_PROP(B, B, A, A) \
    VEC_SWIZZLE_VEC4_PROP(B, B, A, B) \
    VEC_SWIZZLE_VEC4_PROP(B, B, A, C) \
    VEC_SWIZZLE_VEC4_PROP(B, B, A, D) \
    VEC_SWIZZLE_VEC4_PROP(B, B, B, A) \
    VEC_SWIZZLE_VEC4_PROP(B, B, B, B) \
    VEC_SWIZZLE_VEC4_PROP(B, B, B, C) \
    VEC_SWIZZLE_VEC4_PROP(B, B, B, D) \
    VEC_SWIZZLE_VEC4_PROP(B, B, C, A) \
    VEC_SWIZZLE_VEC4_PROP(B, B, C, B) \
    VEC_SWIZZLE_VEC4_PROP(B, B, C, C) \
    VEC_SWIZZLE_VEC4_PROP(B, B, C, D) \
    VEC_SWIZZLE_VEC4_PROP(B, B, D, A) \
    VEC_SWIZZLE_VEC4_PROP(B, B, D, B) \
    VEC_SWIZZLE_VEC4_PROP(B, B, D, C) \
    VEC_SWIZZLE_VEC4_PROP(B, B, D, D) \
    VEC_SWIZZLE_VEC4_PROP(B, C, A, A) \
    VEC_SWIZZLE_VEC4_PROP(B, C, A, B) \
    VEC_SWIZZLE_VEC4_PROP(B, C, A, C) \
    VEC_SWIZZLE_VEC4_PROP(B, C, A, D) \
    VEC_SWIZZLE_VEC4_PROP(B, C, B, A) \
    VEC_SWIZZLE_VEC4_PROP(B, C, B, B) \
    VEC_SWIZZLE_VEC4_PROP(B, C, B, C) \
    VEC_SWIZZLE_VEC4_PROP(B, C, B, D) \
    VEC_SWIZZLE_VEC4_PROP(B, C, C, A) \
    VEC_SWIZZLE_VEC4_PROP(B, C, C, B) \
    VEC_SWIZZLE_VEC4_PROP(B, C, C, C) \
    VEC_SWIZZLE_VEC4_PROP(B, C, C, D) \
    VEC_SWIZZLE_VEC4_PROP(B, C, D, A) \
    VEC_SWIZZLE_VEC4_PROP(B, C, D, B) \
    VEC_SWIZZLE_VEC4_PROP(B, C, D, C) \
    VEC_SWIZZLE_VEC4_PROP(B, C, D, D) \
    VEC_SWIZZLE_VEC4_PROP(B, D, A, A) \
    VEC_SWIZZLE_VEC4_PROP(B, D, A, B) \
    VEC_SWIZZLE_VEC4_PROP(B, D, A, C) \
    VEC_SWIZZLE_VEC4_PROP(B, D, A, D) \
    VEC_SWIZZLE_VEC4_PROP(B, D, B, A) \
    VEC_SWIZZLE_VEC4_PROP(B, D, B, B) \
    VEC_SWIZZLE_VEC4_PROP(B, D, B, C) \
    VEC_SWIZZLE_VEC4_PROP(B, D, B, D) \
    VEC_SWIZZLE_VEC4_PROP(B, D, C, A) \
    VEC_SWIZZLE_VEC4_PROP(B, D, C, B) \
    VEC_SWIZZLE_VEC4_PROP(B, D, C, C) \
    VEC_SWIZZLE_VEC4_PROP(B, D, C, D) \
    VEC_SWIZZLE_VEC4_PROP(B, D, D, A) \
    VEC_SWIZZLE_VEC4_PROP(B, D, D, B) \
    VEC_SWIZZLE_VEC4_PROP(B, D, D, C) \
    VEC_SWIZZLE_VEC4_PROP(B, D, D, D) \
    \
    VEC_SWIZZLE_VEC4_PROP(C, A, A, A) \
    VEC_SWIZZLE_VEC4_PROP(C, A, A, B) \
    VEC_SWIZZLE_VEC4_PROP(C, A, A, C) \
    VEC_SWIZZLE_VEC4_PROP(C, A, A, D) \
    VEC_SWIZZLE_VEC4_PROP(C, A, B, A) \
    VEC_SWIZZLE_VEC4_PROP(C, A, B, B) \
    VEC_SWIZZLE_VEC4_PROP(C, A, B, C) \
    VEC_SWIZZLE_VEC4_PROP(C, A, B, D) \
    VEC_SWIZZLE_VEC4_PROP(C, A, C, A) \
    VEC_SWIZZLE_VEC4_PROP(C, A, C, B) \
    VEC_SWIZZLE_VEC4_PROP(C, A, C, C) \
    VEC_SWIZZLE_VEC4_PROP(C, A, C, D) \
    VEC_SWIZZLE_VEC4_PROP(C, A, D, A) \
    VEC_SWIZZLE_VEC4_PROP(C, A, D, B) \
    VEC_SWIZZLE_VEC4_PROP(C, A, D, C) \
    VEC_SWIZZLE_VEC4_PROP(C, A, D, D) \
    VEC_SWIZZLE_VEC4_PROP(C, B, A, A) \
    VEC_SWIZZLE_VEC4_PROP(C, B, A, B) \
    VEC_SWIZZLE_VEC4_PROP(C, B, A, C) \
    VEC_SWIZZLE_VEC4_PROP(C, B, A, D) \
    VEC_SWIZZLE_VEC4_PROP(C, B, B, A) \
    VEC_SWIZZLE_VEC4_PROP(C, B, B, B) \
    VEC_SWIZZLE_VEC4_PROP(C, B, B, C) \
    VEC_SWIZZLE_VEC4_PROP(C, B, B, D) \
    VEC_SWIZZLE_VEC4_PROP(C, B, C, A) \
    VEC_SWIZZLE_VEC4_PROP(C, B, C, B) \
    VEC_SWIZZLE_VEC4_PROP(C, B, C, C) \
    VEC_SWIZZLE_VEC4_PROP(C, B, C, D) \
    VEC_SWIZZLE_VEC4_PROP(C, B, D, A) \
    VEC_SWIZZLE_VEC4_PROP(C, B, D, B) \
    VEC_SWIZZLE_VEC4_PROP(C, B, D, C) \
    VEC_SWIZZLE_VEC4_PROP(C, B, D, D) \
    VEC_SWIZZLE_VEC4_PROP(C, C, A, A) \
    VEC_SWIZZLE_VEC4_PROP(C, C, A, B) \
    VEC_SWIZZLE_VEC4_PROP(C, C, A, C) \
    VEC_SWIZZLE_VEC4_PROP(C, C, A, D) \
    VEC_SWIZZLE_VEC4_PROP(C, C, B, A) \
    VEC_SWIZZLE_VEC4_PROP(C, C, B, B) \
    VEC_SWIZZLE_VEC4_PROP(C, C, B, C) \
    VEC_SWIZZLE_VEC4_PROP(C, C, B, D) \
    VEC_SWIZZLE_VEC4_PROP(C, C, C, A) \
    VEC_SWIZZLE_VEC4_PROP(C, C, C, B) \
    VEC_SWIZZLE_VEC4_PROP(C, C, C, C) \
    VEC_SWIZZLE_VEC4_PROP(C, C, C, D) \
    VEC_SWIZZLE_VEC4_PROP(C, C, D, A) \
    VEC_SWIZZLE_VEC4_PROP(C, C, D, B) \
    VEC_SWIZZLE_VEC4_PROP(C, C, D, C) \
    VEC_SWIZZLE_VEC4_PROP(C, C, D, D) \
    VEC_SWIZZLE_VEC4_PROP(C, D, A, A) \
    VEC_SWIZZLE_VEC4_PROP(C, D, A, B) \
    VEC_SWIZZLE_VEC4_PROP(C, D, A, C) \
    VEC_SWIZZLE_VEC4_PROP(C, D, A, D) \
    VEC_SWIZZLE_VEC4_PROP(C, D, B, A) \
    VEC_SWIZZLE_VEC4_PROP(C, D, B, B) \
    VEC_SWIZZLE_VEC4_PROP(C, D, B, C) \
    VEC_SWIZZLE_VEC4_PROP(C, D, B, D) \
    VEC_SWIZZLE_VEC4_PROP(C, D, C, A) \
    VEC_SWIZZLE_VEC4_PROP(C, D, C, B) \
    VEC_SWIZZLE_VEC4_PROP(C, D, C, C) \
    VEC_SWIZZLE_VEC4_PROP(C, D, C, D) \
    VEC_SWIZZLE_VEC4_PROP(C, D, D, A) \
    VEC_SWIZZLE_VEC4_PROP(C, D, D, B) \
    VEC_SWIZZLE_VEC4_PROP(C, D, D, C) \
    VEC_SWIZZLE_VEC4_PROP(C, D, D, D) \
    \
    VEC_SWIZZLE_VEC4_PROP(D, A, A, A) \
    VEC_SWIZZLE_VEC4_PROP(D, A, A, B) \
    VEC_SWIZZLE_VEC4_PROP(D, A, A, C) \
    VEC_SWIZZLE_VEC4_PROP(D, A, A, D) \
    VEC_SWIZZLE_VEC4_PROP(D, A, B, A) \
    VEC_SWIZZLE_VEC4_PROP(D, A, B, B) \
    VEC_SWIZZLE_VEC4_PROP(D, A, B, C) \
    VEC_SWIZZLE_VEC4_PROP(D, A, B, D) \
    VEC_SWIZZLE_VEC4_PROP(D, A, C, A) \
    VEC_SWIZZLE_VEC4_PROP(D, A, C, B) \
    VEC_SWIZZLE_VEC4_PROP(D, A, C, C) \
    VEC_SWIZZLE_VEC4_PROP(D, A, C, D) \
    VEC_SWIZZLE_VEC4_PROP(D, A, D, A) \
    VEC_SWIZZLE_VEC4_PROP(D, A, D, B) \
    VEC_SWIZZLE_VEC4_PROP(D, A, D, C) \
    VEC_SWIZZLE_VEC4_PROP(D, A, D, D) \
    VEC_SWIZZLE_VEC4_PROP(D, B, A, A) \
    VEC_SWIZZLE_VEC4_PROP(D, B, A, B) \
    VEC_SWIZZLE_VEC4_PROP(D, B, A, C) \
    VEC_SWIZZLE_VEC4_PROP(D, B, A, D) \
    VEC_SWIZZLE_VEC4_PROP(D, B, B, A) \
    VEC_SWIZZLE_VEC4_PROP(D, B, B, B) \
    VEC_SWIZZLE_VEC4_PROP(D, B, B, C) \
    VEC_SWIZZLE_VEC4_PROP(D, B, B, D) \
    VEC_SWIZZLE_VEC4_PROP(D, B, C, A) \
    VEC_SWIZZLE_VEC4_PROP(D, B, C, B) \
    VEC_SWIZZLE_VEC4_PROP(D, B, C, C) \
    VEC_SWIZZLE_VEC4_PROP(D, B, C, D) \
    VEC_SWIZZLE_VEC4_PROP(D, B, D, A) \
    VEC_SWIZZLE_VEC4_PROP(D, B, D, B) \
    VEC_SWIZZLE_VEC4_PROP(D, B, D, C) \
    VEC_SWIZZLE_VEC4_PROP(D, B, D, D) \
    VEC_SWIZZLE_VEC4_PROP(D, C, A, A) \
    VEC_SWIZZLE_VEC4_PROP(D, C, A, B) \
    VEC_SWIZZLE_VEC4_PROP(D, C, A, C) \
    VEC_SWIZZLE_VEC4_PROP(D, C, A, D) \
    VEC_SWIZZLE_VEC4_PROP(D, C, B, A) \
    VEC_SWIZZLE_VEC4_PROP(D, C, B, B) \
    VEC_SWIZZLE_VEC4_PROP(D, C, B, C) \
    VEC_SWIZZLE_VEC4_PROP(D, C, B, D) \
    VEC_SWIZZLE_VEC4_PROP(D, C, C, A) \
    VEC_SWIZZLE_VEC4_PROP(D, C, C, B) \
    VEC_SWIZZLE_VEC4_PROP(D, C, C, C) \
    VEC_SWIZZLE_VEC4_PROP(D, C, C, D) \
    VEC_SWIZZLE_VEC4_PROP(D, C, D, A) \
    VEC_SWIZZLE_VEC4_PROP(D, C, D, B) \
    VEC_SWIZZLE_VEC4_PROP(D, C, D, C) \
    VEC_SWIZZLE_VEC4_PROP(D, C, D, D) \
    VEC_SWIZZLE_VEC4_PROP(D, D, A, A) \
    VEC_SWIZZLE_VEC4_PROP(D, D, A, B) \
    VEC_SWIZZLE_VEC4_PROP(D, D, A, C) \
    VEC_SWIZZLE_VEC4_PROP(D, D, A, D) \
    VEC_SWIZZLE_VEC4_PROP(D, D, B, A) \
    VEC_SWIZZLE_VEC4_PROP(D, D, B, B) \
    VEC_SWIZZLE_VEC4_PROP(D, D, B, C) \
    VEC_SWIZZLE_VEC4_PROP(D, D, B, D) \
    VEC_SWIZZLE_VEC4_PROP(D, D, C, A) \
    VEC_SWIZZLE_VEC4_PROP(D, D, C, B) \
    VEC_SWIZZLE_VEC4_PROP(D, D, C, C) \
    VEC_SWIZZLE_VEC4_PROP(D, D, C, D) \
    VEC_SWIZZLE_VEC4_PROP(D, D, D, A) \
    VEC_SWIZZLE_VEC4_PROP(D, D, D, B) \
    VEC_SWIZZLE_VEC4_PROP(D, D, D, C) \
    VEC_SWIZZLE_VEC4_PROP(D, D, D, D) \

#define VEC_SWIZZLE_VEC4_FULL_VEC2 \
    VEC_SWIZZLE_VEC2_FROM_VEC4(X, Y, Z, W) \
    VEC_SWIZZLE_VEC2_FROM_VEC4(R, G, B, A) \

#define VEC_SWIZZLE_VEC4_FULL_VEC3 \
    VEC_SWIZZLE_VEC3_FROM_VEC4(X, Y, Z, W) \
    VEC_SWIZZLE_VEC3_FROM_VEC4(R, G, B, A) \

#define VEC_SWIZZLE_VEC4_FULL_VEC4 \
    VEC_SWIZZLE_VEC4_FROM_VEC4(X, Y, Z, W) \
    VEC_SWIZZLE_VEC4_FROM_VEC4(R, G, B, A) \

#define VEC_SWIZZLE_QUAT_FULL_VEC2 \
    VEC_SWIZZLE_VEC2_FROM_VEC4(X, Y, Z, W) \
    
#define VEC_SWIZZLE_QUAT_FULL_VEC3 \
    VEC_SWIZZLE_VEC3_FROM_VEC4(X, Y, Z, W) \

#define VEC_SWIZZLE_QUAT_FULL_VEC4 \
    VEC_SWIZZLE_VEC4_FROM_VEC4(X, Y, Z, W) \

