#pragma once

#define VEC_SWIZZLE_VEC2_PROP(T, A, B) \
public T A##B \
{ \
    get \
    { \
        return new T(A, B); \
    } \
    set \
    { \
        A = value.X; \
        B = value.Y; \
    } \
} 
#define VEC_SWIZZLE_VEC3_PROP(T, A, B, C) \
public T A##B##C \
{ \
    get \
    { \
        return new T(A, B, C); \
    } \
    set \
    { \
        A = value.X; \
        B = value.Y; \
        C = value.Z; \
    } \
}
#define VEC_SWIZZLE_VEC4_PROP(T, A, B, C, D) \
public T A##B##C##D \
{ \
    get \
    { \
        return new T(A, B, C, D); \
    } \
    set \
    { \
        A = value.X; \
        B = value.Y; \
        C = value.Z; \
        D = value.W; \
    } \
}

#define VEC_SWIZZLE_VEC2_FROM_VEC2(T, A, B) \
    VEC_SWIZZLE_VEC2_PROP(T, A, A) \
    VEC_SWIZZLE_VEC2_PROP(T, A, B) \
    VEC_SWIZZLE_VEC2_PROP(T, B, A) \
    VEC_SWIZZLE_VEC2_PROP(T, B, B) \

#define VEC_SWIZZLE_VEC3_FROM_VEC2(T, A, B) \
    VEC_SWIZZLE_VEC3_PROP(T, A, A, A) \
    VEC_SWIZZLE_VEC3_PROP(T, A, A, B) \
    VEC_SWIZZLE_VEC3_PROP(T, A, B, A) \
    VEC_SWIZZLE_VEC3_PROP(T, A, B, B) \
    VEC_SWIZZLE_VEC3_PROP(T, B, A, A) \
    VEC_SWIZZLE_VEC3_PROP(T, B, A, B) \
    VEC_SWIZZLE_VEC3_PROP(T, B, B, A) \
    VEC_SWIZZLE_VEC3_PROP(T, B, B, B) \

#define VEC_SWIZZLE_VEC4_FROM_VEC2(T, A, B) \
    VEC_SWIZZLE_VEC4_PROP(T, A, A, A, A) \
    VEC_SWIZZLE_VEC4_PROP(T, A, A, A, B) \
    VEC_SWIZZLE_VEC4_PROP(T, A, A, B, A) \
    VEC_SWIZZLE_VEC4_PROP(T, A, A, B, B) \
    VEC_SWIZZLE_VEC4_PROP(T, A, B, A, A) \
    VEC_SWIZZLE_VEC4_PROP(T, A, B, A, B) \
    VEC_SWIZZLE_VEC4_PROP(T, A, B, B, A) \
    VEC_SWIZZLE_VEC4_PROP(T, A, B, B, B) \
    VEC_SWIZZLE_VEC4_PROP(T, B, A, A, A) \
    VEC_SWIZZLE_VEC4_PROP(T, B, A, A, B) \
    VEC_SWIZZLE_VEC4_PROP(T, B, A, B, A) \
    VEC_SWIZZLE_VEC4_PROP(T, B, A, B, B) \
    VEC_SWIZZLE_VEC4_PROP(T, B, B, A, A) \
    VEC_SWIZZLE_VEC4_PROP(T, B, B, A, B) \
    VEC_SWIZZLE_VEC4_PROP(T, B, B, B, A) \
    VEC_SWIZZLE_VEC4_PROP(T, B, B, B, B) \

#define VEC_SWIZZLE_VEC2_FULL_VEC2 \
    VEC_SWIZZLE_VEC2_FROM_VEC2(Vector2, X, Y) \
    VEC_SWIZZLE_VEC2_FROM_VEC2(Vector2, U, V) \
    VEC_SWIZZLE_VEC2_FROM_VEC2(Vector2, S, T) \

#define VEC_SWIZZLE_VEC2_FULL_VEC3 \
    VEC_SWIZZLE_VEC3_FROM_VEC2(Vector3, X, Y) \
    VEC_SWIZZLE_VEC3_FROM_VEC2(Vector3, U, V) \
    VEC_SWIZZLE_VEC3_FROM_VEC2(Vector3, S, T) \

#define VEC_SWIZZLE_VEC2_FULL_VEC4 \
    VEC_SWIZZLE_VEC4_FROM_VEC2(Vector4, X, Y) \
    VEC_SWIZZLE_VEC4_FROM_VEC2(Vector4, U, V) \
    VEC_SWIZZLE_VEC4_FROM_VEC2(Vector4, S, T) \

#define VEC_SWIZZLE_IVEC2_FULL_VEC2 \
    VEC_SWIZZLE_VEC2_FROM_VEC2(IVector2, X, Y) \
    VEC_SWIZZLE_VEC2_FROM_VEC2(IVector2, U, V) \
    VEC_SWIZZLE_VEC2_FROM_VEC2(IVector2, S, T) \

#define VEC_SWIZZLE_IVEC2_FULL_VEC3 \
    VEC_SWIZZLE_VEC3_FROM_VEC2(IVector3, X, Y) \
    VEC_SWIZZLE_VEC3_FROM_VEC2(IVector3, U, V) \
    VEC_SWIZZLE_VEC3_FROM_VEC2(IVector3, S, T) \

#define VEC_SWIZZLE_IVEC2_FULL_VEC4 \
    VEC_SWIZZLE_VEC4_FROM_VEC2(IVector4, X, Y) \
    VEC_SWIZZLE_VEC4_FROM_VEC2(IVector4, U, V) \
    VEC_SWIZZLE_VEC4_FROM_VEC2(IVector4, S, T) \

#define VEC_SWIZZLE_VEC2_FROM_VEC3(T, A, B, C) \
    VEC_SWIZZLE_VEC2_PROP(T, A, A) \
    VEC_SWIZZLE_VEC2_PROP(T, A, B) \
    VEC_SWIZZLE_VEC2_PROP(T, A, C) \
    VEC_SWIZZLE_VEC2_PROP(T, B, A) \
    VEC_SWIZZLE_VEC2_PROP(T, B, B) \
    VEC_SWIZZLE_VEC2_PROP(T, B, C) \
    VEC_SWIZZLE_VEC2_PROP(T, C, A) \
    VEC_SWIZZLE_VEC2_PROP(T, C, B) \
    VEC_SWIZZLE_VEC2_PROP(T, C, C) \

#define VEC_SWIZZLE_VEC3_FROM_VEC3(T, A, B, C) \
    VEC_SWIZZLE_VEC3_PROP(T, A, A, A) \
    VEC_SWIZZLE_VEC3_PROP(T, A, A, B) \
    VEC_SWIZZLE_VEC3_PROP(T, A, A, C) \
    VEC_SWIZZLE_VEC3_PROP(T, A, B, A) \
    VEC_SWIZZLE_VEC3_PROP(T, A, B, B) \
    VEC_SWIZZLE_VEC3_PROP(T, A, B, C) \
    VEC_SWIZZLE_VEC3_PROP(T, A, C, A) \
    VEC_SWIZZLE_VEC3_PROP(T, A, C, B) \
    VEC_SWIZZLE_VEC3_PROP(T, A, C, C) \
    VEC_SWIZZLE_VEC3_PROP(T, B, A, A) \
    VEC_SWIZZLE_VEC3_PROP(T, B, A, B) \
    VEC_SWIZZLE_VEC3_PROP(T, B, A, C) \
    VEC_SWIZZLE_VEC3_PROP(T, B, B, A) \
    VEC_SWIZZLE_VEC3_PROP(T, B, B, B) \
    VEC_SWIZZLE_VEC3_PROP(T, B, B, C) \
    VEC_SWIZZLE_VEC3_PROP(T, B, C, A) \
    VEC_SWIZZLE_VEC3_PROP(T, B, C, B) \
    VEC_SWIZZLE_VEC3_PROP(T, B, C, C) \
    VEC_SWIZZLE_VEC3_PROP(T, C, A, A) \
    VEC_SWIZZLE_VEC3_PROP(T, C, A, B) \
    VEC_SWIZZLE_VEC3_PROP(T, C, A, C) \
    VEC_SWIZZLE_VEC3_PROP(T, C, B, A) \
    VEC_SWIZZLE_VEC3_PROP(T, C, B, B) \
    VEC_SWIZZLE_VEC3_PROP(T, C, B, C) \
    VEC_SWIZZLE_VEC3_PROP(T, C, C, A) \
    VEC_SWIZZLE_VEC3_PROP(T, C, C, B) \
    VEC_SWIZZLE_VEC3_PROP(T, C, C, C) \

#define VEC_SWIZZLE_VEC4_FROM_VEC3(T, A, B, C) \
    VEC_SWIZZLE_VEC4_PROP(T, A, A, A, A) \
    VEC_SWIZZLE_VEC4_PROP(T, A, A, A, B) \
    VEC_SWIZZLE_VEC4_PROP(T, A, A, A, C) \
    VEC_SWIZZLE_VEC4_PROP(T, A, A, B, A) \
    VEC_SWIZZLE_VEC4_PROP(T, A, A, B, B) \
    VEC_SWIZZLE_VEC4_PROP(T, A, A, B, C) \
    VEC_SWIZZLE_VEC4_PROP(T, A, A, C, A) \
    VEC_SWIZZLE_VEC4_PROP(T, A, A, C, B) \
    VEC_SWIZZLE_VEC4_PROP(T, A, A, C, C) \
    VEC_SWIZZLE_VEC4_PROP(T, A, B, A, A) \
    VEC_SWIZZLE_VEC4_PROP(T, A, B, A, B) \
    VEC_SWIZZLE_VEC4_PROP(T, A, B, A, C) \
    VEC_SWIZZLE_VEC4_PROP(T, A, B, B, A) \
    VEC_SWIZZLE_VEC4_PROP(T, A, B, B, B) \
    VEC_SWIZZLE_VEC4_PROP(T, A, B, B, C) \
    VEC_SWIZZLE_VEC4_PROP(T, A, B, C, A) \
    VEC_SWIZZLE_VEC4_PROP(T, A, B, C, B) \
    VEC_SWIZZLE_VEC4_PROP(T, A, B, C, C) \
    VEC_SWIZZLE_VEC4_PROP(T, A, C, A, A) \
    VEC_SWIZZLE_VEC4_PROP(T, A, C, A, B) \
    VEC_SWIZZLE_VEC4_PROP(T, A, C, A, C) \
    VEC_SWIZZLE_VEC4_PROP(T, A, C, B, A) \
    VEC_SWIZZLE_VEC4_PROP(T, A, C, B, B) \
    VEC_SWIZZLE_VEC4_PROP(T, A, C, B, C) \
    VEC_SWIZZLE_VEC4_PROP(T, A, C, C, A) \
    VEC_SWIZZLE_VEC4_PROP(T, A, C, C, B) \
    VEC_SWIZZLE_VEC4_PROP(T, A, C, C, C) \
    VEC_SWIZZLE_VEC4_PROP(T, B, A, A, A) \
    VEC_SWIZZLE_VEC4_PROP(T, B, A, A, B) \
    VEC_SWIZZLE_VEC4_PROP(T, B, A, A, C) \
    VEC_SWIZZLE_VEC4_PROP(T, B, A, B, A) \
    VEC_SWIZZLE_VEC4_PROP(T, B, A, B, B) \
    VEC_SWIZZLE_VEC4_PROP(T, B, A, B, C) \
    VEC_SWIZZLE_VEC4_PROP(T, B, A, C, A) \
    VEC_SWIZZLE_VEC4_PROP(T, B, A, C, B) \
    VEC_SWIZZLE_VEC4_PROP(T, B, A, C, C) \
    VEC_SWIZZLE_VEC4_PROP(T, B, B, A, A) \
    VEC_SWIZZLE_VEC4_PROP(T, B, B, A, B) \
    VEC_SWIZZLE_VEC4_PROP(T, B, B, A, C) \
    VEC_SWIZZLE_VEC4_PROP(T, B, B, B, A) \
    VEC_SWIZZLE_VEC4_PROP(T, B, B, B, B) \
    VEC_SWIZZLE_VEC4_PROP(T, B, B, B, C) \
    VEC_SWIZZLE_VEC4_PROP(T, B, B, C, A) \
    VEC_SWIZZLE_VEC4_PROP(T, B, B, C, B) \
    VEC_SWIZZLE_VEC4_PROP(T, B, B, C, C) \
    VEC_SWIZZLE_VEC4_PROP(T, B, C, A, A) \
    VEC_SWIZZLE_VEC4_PROP(T, B, C, A, B) \
    VEC_SWIZZLE_VEC4_PROP(T, B, C, A, C) \
    VEC_SWIZZLE_VEC4_PROP(T, B, C, B, A) \
    VEC_SWIZZLE_VEC4_PROP(T, B, C, B, B) \
    VEC_SWIZZLE_VEC4_PROP(T, B, C, B, C) \
    VEC_SWIZZLE_VEC4_PROP(T, B, C, C, A) \
    VEC_SWIZZLE_VEC4_PROP(T, B, C, C, B) \
    VEC_SWIZZLE_VEC4_PROP(T, B, C, C, C) \
    VEC_SWIZZLE_VEC4_PROP(T, C, A, A, A) \
    VEC_SWIZZLE_VEC4_PROP(T, C, A, A, B) \
    VEC_SWIZZLE_VEC4_PROP(T, C, A, A, C) \
    VEC_SWIZZLE_VEC4_PROP(T, C, A, B, A) \
    VEC_SWIZZLE_VEC4_PROP(T, C, A, B, B) \
    VEC_SWIZZLE_VEC4_PROP(T, C, A, B, C) \
    VEC_SWIZZLE_VEC4_PROP(T, C, A, C, A) \
    VEC_SWIZZLE_VEC4_PROP(T, C, A, C, B) \
    VEC_SWIZZLE_VEC4_PROP(T, C, A, C, C) \
    VEC_SWIZZLE_VEC4_PROP(T, C, B, A, A) \
    VEC_SWIZZLE_VEC4_PROP(T, C, B, A, B) \
    VEC_SWIZZLE_VEC4_PROP(T, C, B, A, C) \
    VEC_SWIZZLE_VEC4_PROP(T, C, B, B, A) \
    VEC_SWIZZLE_VEC4_PROP(T, C, B, B, B) \
    VEC_SWIZZLE_VEC4_PROP(T, C, B, B, C) \
    VEC_SWIZZLE_VEC4_PROP(T, C, B, C, A) \
    VEC_SWIZZLE_VEC4_PROP(T, C, B, C, B) \
    VEC_SWIZZLE_VEC4_PROP(T, C, B, C, C) \
    VEC_SWIZZLE_VEC4_PROP(T, C, C, A, A) \
    VEC_SWIZZLE_VEC4_PROP(T, C, C, A, B) \
    VEC_SWIZZLE_VEC4_PROP(T, C, C, A, C) \
    VEC_SWIZZLE_VEC4_PROP(T, C, C, B, A) \
    VEC_SWIZZLE_VEC4_PROP(T, C, C, B, B) \
    VEC_SWIZZLE_VEC4_PROP(T, C, C, B, C) \
    VEC_SWIZZLE_VEC4_PROP(T, C, C, C, A) \
    VEC_SWIZZLE_VEC4_PROP(T, C, C, C, B) \
    VEC_SWIZZLE_VEC4_PROP(T, C, C, C, C) \

#define VEC_SWIZZLE_VEC3_FULL_VEC2 \
    VEC_SWIZZLE_VEC2_FROM_VEC3(Vector2, X, Y, Z) \
    VEC_SWIZZLE_VEC2_FROM_VEC3(Vector2, R, G, B) \
    VEC_SWIZZLE_VEC2_FROM_VEC3(Vector2, U, V, W) \

#define VEC_SWIZZLE_VEC3_FULL_VEC3 \
    VEC_SWIZZLE_VEC3_FROM_VEC3(Vector3, X, Y, Z) \
    VEC_SWIZZLE_VEC3_FROM_VEC3(Vector3, R, G, B) \
    VEC_SWIZZLE_VEC3_FROM_VEC3(Vector3, U, V, W) \

#define VEC_SWIZZLE_VEC3_FULL_VEC4 \
    VEC_SWIZZLE_VEC4_FROM_VEC3(Vector4, X, Y, Z) \
    VEC_SWIZZLE_VEC4_FROM_VEC3(Vector4, R, G, B) \
    VEC_SWIZZLE_VEC4_FROM_VEC3(Vector4, U, V, W) \

#define VEC_SWIZZLE_IVEC3_FULL_VEC2 \
    VEC_SWIZZLE_VEC2_FROM_VEC3(IVector2, X, Y, Z) \
    VEC_SWIZZLE_VEC2_FROM_VEC3(IVector2, R, G, B) \
    VEC_SWIZZLE_VEC2_FROM_VEC3(IVector2, U, V, W) \

#define VEC_SWIZZLE_IVEC3_FULL_VEC3 \
    VEC_SWIZZLE_VEC3_FROM_VEC3(IVector3, X, Y, Z) \
    VEC_SWIZZLE_VEC3_FROM_VEC3(IVector3, R, G, B) \
    VEC_SWIZZLE_VEC3_FROM_VEC3(IVector3, U, V, W) \

#define VEC_SWIZZLE_IVEC3_FULL_VEC4 \
    VEC_SWIZZLE_VEC4_FROM_VEC3(IVector4, X, Y, Z) \
    VEC_SWIZZLE_VEC4_FROM_VEC3(IVector4, R, G, B) \
    VEC_SWIZZLE_VEC4_FROM_VEC3(IVector4, U, V, W) \

#define VEC_SWIZZLE_VEC2_FROM_VEC4(T, A, B, C, D) \
    VEC_SWIZZLE_VEC2_PROP(T, A, A) \
    VEC_SWIZZLE_VEC2_PROP(T, A, B) \
    VEC_SWIZZLE_VEC2_PROP(T, A, C) \
    VEC_SWIZZLE_VEC2_PROP(T, A, D) \
    VEC_SWIZZLE_VEC2_PROP(T, B, A) \
    VEC_SWIZZLE_VEC2_PROP(T, B, B) \
    VEC_SWIZZLE_VEC2_PROP(T, B, C) \
    VEC_SWIZZLE_VEC2_PROP(T, B, D) \
    VEC_SWIZZLE_VEC2_PROP(T, C, A) \
    VEC_SWIZZLE_VEC2_PROP(T, C, B) \
    VEC_SWIZZLE_VEC2_PROP(T, C, C) \
    VEC_SWIZZLE_VEC2_PROP(T, C, D) \
    VEC_SWIZZLE_VEC2_PROP(T, D, A) \
    VEC_SWIZZLE_VEC2_PROP(T, D, B) \
    VEC_SWIZZLE_VEC2_PROP(T, D, C) \
    VEC_SWIZZLE_VEC2_PROP(T, D, D) \

#define VEC_SWIZZLE_VEC3_FROM_VEC4(T, A, B, C, D) \
    VEC_SWIZZLE_VEC3_PROP(T, A, A, A) \
    VEC_SWIZZLE_VEC3_PROP(T, A, A, B) \
    VEC_SWIZZLE_VEC3_PROP(T, A, A, C) \
    VEC_SWIZZLE_VEC3_PROP(T, A, A, D) \
    VEC_SWIZZLE_VEC3_PROP(T, A, B, A) \
    VEC_SWIZZLE_VEC3_PROP(T, A, B, B) \
    VEC_SWIZZLE_VEC3_PROP(T, A, B, C) \
    VEC_SWIZZLE_VEC3_PROP(T, A, B, D) \
    VEC_SWIZZLE_VEC3_PROP(T, A, C, A) \
    VEC_SWIZZLE_VEC3_PROP(T, A, C, B) \
    VEC_SWIZZLE_VEC3_PROP(T, A, C, C) \
    VEC_SWIZZLE_VEC3_PROP(T, A, C, D) \
    VEC_SWIZZLE_VEC3_PROP(T, A, D, A) \
    VEC_SWIZZLE_VEC3_PROP(T, A, D, B) \
    VEC_SWIZZLE_VEC3_PROP(T, A, D, C) \
    VEC_SWIZZLE_VEC3_PROP(T, A, D, D) \
    VEC_SWIZZLE_VEC3_PROP(T, B, A, A) \
    VEC_SWIZZLE_VEC3_PROP(T, B, A, B) \
    VEC_SWIZZLE_VEC3_PROP(T, B, A, C) \
    VEC_SWIZZLE_VEC3_PROP(T, B, A, D) \
    VEC_SWIZZLE_VEC3_PROP(T, B, B, A) \
    VEC_SWIZZLE_VEC3_PROP(T, B, B, B) \
    VEC_SWIZZLE_VEC3_PROP(T, B, B, C) \
    VEC_SWIZZLE_VEC3_PROP(T, B, B, D) \
    VEC_SWIZZLE_VEC3_PROP(T, B, C, A) \
    VEC_SWIZZLE_VEC3_PROP(T, B, C, B) \
    VEC_SWIZZLE_VEC3_PROP(T, B, C, C) \
    VEC_SWIZZLE_VEC3_PROP(T, B, C, D) \
    VEC_SWIZZLE_VEC3_PROP(T, B, D, A) \
    VEC_SWIZZLE_VEC3_PROP(T, B, D, B) \
    VEC_SWIZZLE_VEC3_PROP(T, B, D, C) \
    VEC_SWIZZLE_VEC3_PROP(T, B, D, D) \
    VEC_SWIZZLE_VEC3_PROP(T, C, A, A) \
    VEC_SWIZZLE_VEC3_PROP(T, C, A, B) \
    VEC_SWIZZLE_VEC3_PROP(T, C, A, C) \
    VEC_SWIZZLE_VEC3_PROP(T, C, A, D) \
    VEC_SWIZZLE_VEC3_PROP(T, C, B, A) \
    VEC_SWIZZLE_VEC3_PROP(T, C, B, B) \
    VEC_SWIZZLE_VEC3_PROP(T, C, B, C) \
    VEC_SWIZZLE_VEC3_PROP(T, C, B, D) \
    VEC_SWIZZLE_VEC3_PROP(T, C, C, A) \
    VEC_SWIZZLE_VEC3_PROP(T, C, C, B) \
    VEC_SWIZZLE_VEC3_PROP(T, C, C, C) \
    VEC_SWIZZLE_VEC3_PROP(T, C, C, D) \
    VEC_SWIZZLE_VEC3_PROP(T, C, D, A) \
    VEC_SWIZZLE_VEC3_PROP(T, C, D, B) \
    VEC_SWIZZLE_VEC3_PROP(T, C, D, C) \
    VEC_SWIZZLE_VEC3_PROP(T, C, D, D) \
    VEC_SWIZZLE_VEC3_PROP(T, D, A, A) \
    VEC_SWIZZLE_VEC3_PROP(T, D, A, B) \
    VEC_SWIZZLE_VEC3_PROP(T, D, A, C) \
    VEC_SWIZZLE_VEC3_PROP(T, D, A, D) \
    VEC_SWIZZLE_VEC3_PROP(T, D, B, A) \
    VEC_SWIZZLE_VEC3_PROP(T, D, B, B) \
    VEC_SWIZZLE_VEC3_PROP(T, D, B, C) \
    VEC_SWIZZLE_VEC3_PROP(T, D, B, D) \
    VEC_SWIZZLE_VEC3_PROP(T, D, C, A) \
    VEC_SWIZZLE_VEC3_PROP(T, D, C, B) \
    VEC_SWIZZLE_VEC3_PROP(T, D, C, C) \
    VEC_SWIZZLE_VEC3_PROP(T, D, C, D) \
    VEC_SWIZZLE_VEC3_PROP(T, D, D, A) \
    VEC_SWIZZLE_VEC3_PROP(T, D, D, B) \
    VEC_SWIZZLE_VEC3_PROP(T, D, D, C) \
    VEC_SWIZZLE_VEC3_PROP(T, D, D, D) \

#define VEC_SWIZZLE_VEC4_FROM_VEC4(T, A, B, C, D) \
    VEC_SWIZZLE_VEC4_PROP(T, A, A, A, A) \
    VEC_SWIZZLE_VEC4_PROP(T, A, A, A, B) \
    VEC_SWIZZLE_VEC4_PROP(T, A, A, A, C) \
    VEC_SWIZZLE_VEC4_PROP(T, A, A, A, D) \
    VEC_SWIZZLE_VEC4_PROP(T, A, A, B, A) \
    VEC_SWIZZLE_VEC4_PROP(T, A, A, B, B) \
    VEC_SWIZZLE_VEC4_PROP(T, A, A, B, C) \
    VEC_SWIZZLE_VEC4_PROP(T, A, A, B, D) \
    VEC_SWIZZLE_VEC4_PROP(T, A, A, C, A) \
    VEC_SWIZZLE_VEC4_PROP(T, A, A, C, B) \
    VEC_SWIZZLE_VEC4_PROP(T, A, A, C, C) \
    VEC_SWIZZLE_VEC4_PROP(T, A, A, C, D) \
    VEC_SWIZZLE_VEC4_PROP(T, A, A, D, A) \
    VEC_SWIZZLE_VEC4_PROP(T, A, A, D, B) \
    VEC_SWIZZLE_VEC4_PROP(T, A, A, D, C) \
    VEC_SWIZZLE_VEC4_PROP(T, A, A, D, D) \
    VEC_SWIZZLE_VEC4_PROP(T, A, B, A, A) \
    VEC_SWIZZLE_VEC4_PROP(T, A, B, A, B) \
    VEC_SWIZZLE_VEC4_PROP(T, A, B, A, C) \
    VEC_SWIZZLE_VEC4_PROP(T, A, B, A, D) \
    VEC_SWIZZLE_VEC4_PROP(T, A, B, B, A) \
    VEC_SWIZZLE_VEC4_PROP(T, A, B, B, B) \
    VEC_SWIZZLE_VEC4_PROP(T, A, B, B, C) \
    VEC_SWIZZLE_VEC4_PROP(T, A, B, B, D) \
    VEC_SWIZZLE_VEC4_PROP(T, A, B, C, A) \
    VEC_SWIZZLE_VEC4_PROP(T, A, B, C, B) \
    VEC_SWIZZLE_VEC4_PROP(T, A, B, C, C) \
    VEC_SWIZZLE_VEC4_PROP(T, A, B, C, D) \
    VEC_SWIZZLE_VEC4_PROP(T, A, B, D, A) \
    VEC_SWIZZLE_VEC4_PROP(T, A, B, D, B) \
    VEC_SWIZZLE_VEC4_PROP(T, A, B, D, C) \
    VEC_SWIZZLE_VEC4_PROP(T, A, B, D, D) \
    VEC_SWIZZLE_VEC4_PROP(T, A, C, A, A) \
    VEC_SWIZZLE_VEC4_PROP(T, A, C, A, B) \
    VEC_SWIZZLE_VEC4_PROP(T, A, C, A, C) \
    VEC_SWIZZLE_VEC4_PROP(T, A, C, A, D) \
    VEC_SWIZZLE_VEC4_PROP(T, A, C, B, A) \
    VEC_SWIZZLE_VEC4_PROP(T, A, C, B, B) \
    VEC_SWIZZLE_VEC4_PROP(T, A, C, B, C) \
    VEC_SWIZZLE_VEC4_PROP(T, A, C, B, D) \
    VEC_SWIZZLE_VEC4_PROP(T, A, C, C, A) \
    VEC_SWIZZLE_VEC4_PROP(T, A, C, C, B) \
    VEC_SWIZZLE_VEC4_PROP(T, A, C, C, C) \
    VEC_SWIZZLE_VEC4_PROP(T, A, C, C, D) \
    VEC_SWIZZLE_VEC4_PROP(T, A, C, D, A) \
    VEC_SWIZZLE_VEC4_PROP(T, A, C, D, B) \
    VEC_SWIZZLE_VEC4_PROP(T, A, C, D, C) \
    VEC_SWIZZLE_VEC4_PROP(T, A, C, D, D) \
    VEC_SWIZZLE_VEC4_PROP(T, A, D, A, A) \
    VEC_SWIZZLE_VEC4_PROP(T, A, D, A, B) \
    VEC_SWIZZLE_VEC4_PROP(T, A, D, A, C) \
    VEC_SWIZZLE_VEC4_PROP(T, A, D, A, D) \
    VEC_SWIZZLE_VEC4_PROP(T, A, D, B, A) \
    VEC_SWIZZLE_VEC4_PROP(T, A, D, B, B) \
    VEC_SWIZZLE_VEC4_PROP(T, A, D, B, C) \
    VEC_SWIZZLE_VEC4_PROP(T, A, D, B, D) \
    VEC_SWIZZLE_VEC4_PROP(T, A, D, C, A) \
    VEC_SWIZZLE_VEC4_PROP(T, A, D, C, B) \
    VEC_SWIZZLE_VEC4_PROP(T, A, D, C, C) \
    VEC_SWIZZLE_VEC4_PROP(T, A, D, C, D) \
    VEC_SWIZZLE_VEC4_PROP(T, A, D, D, A) \
    VEC_SWIZZLE_VEC4_PROP(T, A, D, D, B) \
    VEC_SWIZZLE_VEC4_PROP(T, A, D, D, C) \
    VEC_SWIZZLE_VEC4_PROP(T, A, D, D, D) \
    \
    VEC_SWIZZLE_VEC4_PROP(T, B, A, A, A) \
    VEC_SWIZZLE_VEC4_PROP(T, B, A, A, B) \
    VEC_SWIZZLE_VEC4_PROP(T, B, A, A, C) \
    VEC_SWIZZLE_VEC4_PROP(T, B, A, A, D) \
    VEC_SWIZZLE_VEC4_PROP(T, B, A, B, A) \
    VEC_SWIZZLE_VEC4_PROP(T, B, A, B, B) \
    VEC_SWIZZLE_VEC4_PROP(T, B, A, B, C) \
    VEC_SWIZZLE_VEC4_PROP(T, B, A, B, D) \
    VEC_SWIZZLE_VEC4_PROP(T, B, A, C, A) \
    VEC_SWIZZLE_VEC4_PROP(T, B, A, C, B) \
    VEC_SWIZZLE_VEC4_PROP(T, B, A, C, C) \
    VEC_SWIZZLE_VEC4_PROP(T, B, A, C, D) \
    VEC_SWIZZLE_VEC4_PROP(T, B, A, D, A) \
    VEC_SWIZZLE_VEC4_PROP(T, B, A, D, B) \
    VEC_SWIZZLE_VEC4_PROP(T, B, A, D, C) \
    VEC_SWIZZLE_VEC4_PROP(T, B, A, D, D) \
    VEC_SWIZZLE_VEC4_PROP(T, B, B, A, A) \
    VEC_SWIZZLE_VEC4_PROP(T, B, B, A, B) \
    VEC_SWIZZLE_VEC4_PROP(T, B, B, A, C) \
    VEC_SWIZZLE_VEC4_PROP(T, B, B, A, D) \
    VEC_SWIZZLE_VEC4_PROP(T, B, B, B, A) \
    VEC_SWIZZLE_VEC4_PROP(T, B, B, B, B) \
    VEC_SWIZZLE_VEC4_PROP(T, B, B, B, C) \
    VEC_SWIZZLE_VEC4_PROP(T, B, B, B, D) \
    VEC_SWIZZLE_VEC4_PROP(T, B, B, C, A) \
    VEC_SWIZZLE_VEC4_PROP(T, B, B, C, B) \
    VEC_SWIZZLE_VEC4_PROP(T, B, B, C, C) \
    VEC_SWIZZLE_VEC4_PROP(T, B, B, C, D) \
    VEC_SWIZZLE_VEC4_PROP(T, B, B, D, A) \
    VEC_SWIZZLE_VEC4_PROP(T, B, B, D, B) \
    VEC_SWIZZLE_VEC4_PROP(T, B, B, D, C) \
    VEC_SWIZZLE_VEC4_PROP(T, B, B, D, D) \
    VEC_SWIZZLE_VEC4_PROP(T, B, C, A, A) \
    VEC_SWIZZLE_VEC4_PROP(T, B, C, A, B) \
    VEC_SWIZZLE_VEC4_PROP(T, B, C, A, C) \
    VEC_SWIZZLE_VEC4_PROP(T, B, C, A, D) \
    VEC_SWIZZLE_VEC4_PROP(T, B, C, B, A) \
    VEC_SWIZZLE_VEC4_PROP(T, B, C, B, B) \
    VEC_SWIZZLE_VEC4_PROP(T, B, C, B, C) \
    VEC_SWIZZLE_VEC4_PROP(T, B, C, B, D) \
    VEC_SWIZZLE_VEC4_PROP(T, B, C, C, A) \
    VEC_SWIZZLE_VEC4_PROP(T, B, C, C, B) \
    VEC_SWIZZLE_VEC4_PROP(T, B, C, C, C) \
    VEC_SWIZZLE_VEC4_PROP(T, B, C, C, D) \
    VEC_SWIZZLE_VEC4_PROP(T, B, C, D, A) \
    VEC_SWIZZLE_VEC4_PROP(T, B, C, D, B) \
    VEC_SWIZZLE_VEC4_PROP(T, B, C, D, C) \
    VEC_SWIZZLE_VEC4_PROP(T, B, C, D, D) \
    VEC_SWIZZLE_VEC4_PROP(T, B, D, A, A) \
    VEC_SWIZZLE_VEC4_PROP(T, B, D, A, B) \
    VEC_SWIZZLE_VEC4_PROP(T, B, D, A, C) \
    VEC_SWIZZLE_VEC4_PROP(T, B, D, A, D) \
    VEC_SWIZZLE_VEC4_PROP(T, B, D, B, A) \
    VEC_SWIZZLE_VEC4_PROP(T, B, D, B, B) \
    VEC_SWIZZLE_VEC4_PROP(T, B, D, B, C) \
    VEC_SWIZZLE_VEC4_PROP(T, B, D, B, D) \
    VEC_SWIZZLE_VEC4_PROP(T, B, D, C, A) \
    VEC_SWIZZLE_VEC4_PROP(T, B, D, C, B) \
    VEC_SWIZZLE_VEC4_PROP(T, B, D, C, C) \
    VEC_SWIZZLE_VEC4_PROP(T, B, D, C, D) \
    VEC_SWIZZLE_VEC4_PROP(T, B, D, D, A) \
    VEC_SWIZZLE_VEC4_PROP(T, B, D, D, B) \
    VEC_SWIZZLE_VEC4_PROP(T, B, D, D, C) \
    VEC_SWIZZLE_VEC4_PROP(T, B, D, D, D) \
    \
    VEC_SWIZZLE_VEC4_PROP(T, C, A, A, A) \
    VEC_SWIZZLE_VEC4_PROP(T, C, A, A, B) \
    VEC_SWIZZLE_VEC4_PROP(T, C, A, A, C) \
    VEC_SWIZZLE_VEC4_PROP(T, C, A, A, D) \
    VEC_SWIZZLE_VEC4_PROP(T, C, A, B, A) \
    VEC_SWIZZLE_VEC4_PROP(T, C, A, B, B) \
    VEC_SWIZZLE_VEC4_PROP(T, C, A, B, C) \
    VEC_SWIZZLE_VEC4_PROP(T, C, A, B, D) \
    VEC_SWIZZLE_VEC4_PROP(T, C, A, C, A) \
    VEC_SWIZZLE_VEC4_PROP(T, C, A, C, B) \
    VEC_SWIZZLE_VEC4_PROP(T, C, A, C, C) \
    VEC_SWIZZLE_VEC4_PROP(T, C, A, C, D) \
    VEC_SWIZZLE_VEC4_PROP(T, C, A, D, A) \
    VEC_SWIZZLE_VEC4_PROP(T, C, A, D, B) \
    VEC_SWIZZLE_VEC4_PROP(T, C, A, D, C) \
    VEC_SWIZZLE_VEC4_PROP(T, C, A, D, D) \
    VEC_SWIZZLE_VEC4_PROP(T, C, B, A, A) \
    VEC_SWIZZLE_VEC4_PROP(T, C, B, A, B) \
    VEC_SWIZZLE_VEC4_PROP(T, C, B, A, C) \
    VEC_SWIZZLE_VEC4_PROP(T, C, B, A, D) \
    VEC_SWIZZLE_VEC4_PROP(T, C, B, B, A) \
    VEC_SWIZZLE_VEC4_PROP(T, C, B, B, B) \
    VEC_SWIZZLE_VEC4_PROP(T, C, B, B, C) \
    VEC_SWIZZLE_VEC4_PROP(T, C, B, B, D) \
    VEC_SWIZZLE_VEC4_PROP(T, C, B, C, A) \
    VEC_SWIZZLE_VEC4_PROP(T, C, B, C, B) \
    VEC_SWIZZLE_VEC4_PROP(T, C, B, C, C) \
    VEC_SWIZZLE_VEC4_PROP(T, C, B, C, D) \
    VEC_SWIZZLE_VEC4_PROP(T, C, B, D, A) \
    VEC_SWIZZLE_VEC4_PROP(T, C, B, D, B) \
    VEC_SWIZZLE_VEC4_PROP(T, C, B, D, C) \
    VEC_SWIZZLE_VEC4_PROP(T, C, B, D, D) \
    VEC_SWIZZLE_VEC4_PROP(T, C, C, A, A) \
    VEC_SWIZZLE_VEC4_PROP(T, C, C, A, B) \
    VEC_SWIZZLE_VEC4_PROP(T, C, C, A, C) \
    VEC_SWIZZLE_VEC4_PROP(T, C, C, A, D) \
    VEC_SWIZZLE_VEC4_PROP(T, C, C, B, A) \
    VEC_SWIZZLE_VEC4_PROP(T, C, C, B, B) \
    VEC_SWIZZLE_VEC4_PROP(T, C, C, B, C) \
    VEC_SWIZZLE_VEC4_PROP(T, C, C, B, D) \
    VEC_SWIZZLE_VEC4_PROP(T, C, C, C, A) \
    VEC_SWIZZLE_VEC4_PROP(T, C, C, C, B) \
    VEC_SWIZZLE_VEC4_PROP(T, C, C, C, C) \
    VEC_SWIZZLE_VEC4_PROP(T, C, C, C, D) \
    VEC_SWIZZLE_VEC4_PROP(T, C, C, D, A) \
    VEC_SWIZZLE_VEC4_PROP(T, C, C, D, B) \
    VEC_SWIZZLE_VEC4_PROP(T, C, C, D, C) \
    VEC_SWIZZLE_VEC4_PROP(T, C, C, D, D) \
    VEC_SWIZZLE_VEC4_PROP(T, C, D, A, A) \
    VEC_SWIZZLE_VEC4_PROP(T, C, D, A, B) \
    VEC_SWIZZLE_VEC4_PROP(T, C, D, A, C) \
    VEC_SWIZZLE_VEC4_PROP(T, C, D, A, D) \
    VEC_SWIZZLE_VEC4_PROP(T, C, D, B, A) \
    VEC_SWIZZLE_VEC4_PROP(T, C, D, B, B) \
    VEC_SWIZZLE_VEC4_PROP(T, C, D, B, C) \
    VEC_SWIZZLE_VEC4_PROP(T, C, D, B, D) \
    VEC_SWIZZLE_VEC4_PROP(T, C, D, C, A) \
    VEC_SWIZZLE_VEC4_PROP(T, C, D, C, B) \
    VEC_SWIZZLE_VEC4_PROP(T, C, D, C, C) \
    VEC_SWIZZLE_VEC4_PROP(T, C, D, C, D) \
    VEC_SWIZZLE_VEC4_PROP(T, C, D, D, A) \
    VEC_SWIZZLE_VEC4_PROP(T, C, D, D, B) \
    VEC_SWIZZLE_VEC4_PROP(T, C, D, D, C) \
    VEC_SWIZZLE_VEC4_PROP(T, C, D, D, D) \
    \
    VEC_SWIZZLE_VEC4_PROP(T, D, A, A, A) \
    VEC_SWIZZLE_VEC4_PROP(T, D, A, A, B) \
    VEC_SWIZZLE_VEC4_PROP(T, D, A, A, C) \
    VEC_SWIZZLE_VEC4_PROP(T, D, A, A, D) \
    VEC_SWIZZLE_VEC4_PROP(T, D, A, B, A) \
    VEC_SWIZZLE_VEC4_PROP(T, D, A, B, B) \
    VEC_SWIZZLE_VEC4_PROP(T, D, A, B, C) \
    VEC_SWIZZLE_VEC4_PROP(T, D, A, B, D) \
    VEC_SWIZZLE_VEC4_PROP(T, D, A, C, A) \
    VEC_SWIZZLE_VEC4_PROP(T, D, A, C, B) \
    VEC_SWIZZLE_VEC4_PROP(T, D, A, C, C) \
    VEC_SWIZZLE_VEC4_PROP(T, D, A, C, D) \
    VEC_SWIZZLE_VEC4_PROP(T, D, A, D, A) \
    VEC_SWIZZLE_VEC4_PROP(T, D, A, D, B) \
    VEC_SWIZZLE_VEC4_PROP(T, D, A, D, C) \
    VEC_SWIZZLE_VEC4_PROP(T, D, A, D, D) \
    VEC_SWIZZLE_VEC4_PROP(T, D, B, A, A) \
    VEC_SWIZZLE_VEC4_PROP(T, D, B, A, B) \
    VEC_SWIZZLE_VEC4_PROP(T, D, B, A, C) \
    VEC_SWIZZLE_VEC4_PROP(T, D, B, A, D) \
    VEC_SWIZZLE_VEC4_PROP(T, D, B, B, A) \
    VEC_SWIZZLE_VEC4_PROP(T, D, B, B, B) \
    VEC_SWIZZLE_VEC4_PROP(T, D, B, B, C) \
    VEC_SWIZZLE_VEC4_PROP(T, D, B, B, D) \
    VEC_SWIZZLE_VEC4_PROP(T, D, B, C, A) \
    VEC_SWIZZLE_VEC4_PROP(T, D, B, C, B) \
    VEC_SWIZZLE_VEC4_PROP(T, D, B, C, C) \
    VEC_SWIZZLE_VEC4_PROP(T, D, B, C, D) \
    VEC_SWIZZLE_VEC4_PROP(T, D, B, D, A) \
    VEC_SWIZZLE_VEC4_PROP(T, D, B, D, B) \
    VEC_SWIZZLE_VEC4_PROP(T, D, B, D, C) \
    VEC_SWIZZLE_VEC4_PROP(T, D, B, D, D) \
    VEC_SWIZZLE_VEC4_PROP(T, D, C, A, A) \
    VEC_SWIZZLE_VEC4_PROP(T, D, C, A, B) \
    VEC_SWIZZLE_VEC4_PROP(T, D, C, A, C) \
    VEC_SWIZZLE_VEC4_PROP(T, D, C, A, D) \
    VEC_SWIZZLE_VEC4_PROP(T, D, C, B, A) \
    VEC_SWIZZLE_VEC4_PROP(T, D, C, B, B) \
    VEC_SWIZZLE_VEC4_PROP(T, D, C, B, C) \
    VEC_SWIZZLE_VEC4_PROP(T, D, C, B, D) \
    VEC_SWIZZLE_VEC4_PROP(T, D, C, C, A) \
    VEC_SWIZZLE_VEC4_PROP(T, D, C, C, B) \
    VEC_SWIZZLE_VEC4_PROP(T, D, C, C, C) \
    VEC_SWIZZLE_VEC4_PROP(T, D, C, C, D) \
    VEC_SWIZZLE_VEC4_PROP(T, D, C, D, A) \
    VEC_SWIZZLE_VEC4_PROP(T, D, C, D, B) \
    VEC_SWIZZLE_VEC4_PROP(T, D, C, D, C) \
    VEC_SWIZZLE_VEC4_PROP(T, D, C, D, D) \
    VEC_SWIZZLE_VEC4_PROP(T, D, D, A, A) \
    VEC_SWIZZLE_VEC4_PROP(T, D, D, A, B) \
    VEC_SWIZZLE_VEC4_PROP(T, D, D, A, C) \
    VEC_SWIZZLE_VEC4_PROP(T, D, D, A, D) \
    VEC_SWIZZLE_VEC4_PROP(T, D, D, B, A) \
    VEC_SWIZZLE_VEC4_PROP(T, D, D, B, B) \
    VEC_SWIZZLE_VEC4_PROP(T, D, D, B, C) \
    VEC_SWIZZLE_VEC4_PROP(T, D, D, B, D) \
    VEC_SWIZZLE_VEC4_PROP(T, D, D, C, A) \
    VEC_SWIZZLE_VEC4_PROP(T, D, D, C, B) \
    VEC_SWIZZLE_VEC4_PROP(T, D, D, C, C) \
    VEC_SWIZZLE_VEC4_PROP(T, D, D, C, D) \
    VEC_SWIZZLE_VEC4_PROP(T, D, D, D, A) \
    VEC_SWIZZLE_VEC4_PROP(T, D, D, D, B) \
    VEC_SWIZZLE_VEC4_PROP(T, D, D, D, C) \
    VEC_SWIZZLE_VEC4_PROP(T, D, D, D, D) \

#define VEC_SWIZZLE_VEC4_FULL_VEC2 \
    VEC_SWIZZLE_VEC2_FROM_VEC4(Vector2, X, Y, Z, W) \
    VEC_SWIZZLE_VEC2_FROM_VEC4(Vector2, R, G, B, A) \

#define VEC_SWIZZLE_VEC4_FULL_VEC3 \
    VEC_SWIZZLE_VEC3_FROM_VEC4(Vector3, X, Y, Z, W) \
    VEC_SWIZZLE_VEC3_FROM_VEC4(Vector3, R, G, B, A) \

#define VEC_SWIZZLE_VEC4_FULL_VEC4 \
    VEC_SWIZZLE_VEC4_FROM_VEC4(Vector4, X, Y, Z, W) \
    VEC_SWIZZLE_VEC4_FROM_VEC4(Vector4, R, G, B, A) \

#define VEC_SWIZZLE_IVEC4_FULL_VEC2 \
    VEC_SWIZZLE_VEC2_FROM_VEC4(IVector2, X, Y, Z, W) \
    VEC_SWIZZLE_VEC2_FROM_VEC4(IVector2, R, G, B, A) \

#define VEC_SWIZZLE_IVEC4_FULL_VEC3 \
    VEC_SWIZZLE_VEC3_FROM_VEC4(IVector3, X, Y, Z, W) \
    VEC_SWIZZLE_VEC3_FROM_VEC4(IVector3, R, G, B, A) \

#define VEC_SWIZZLE_IVEC4_FULL_VEC4 \
    VEC_SWIZZLE_VEC4_FROM_VEC4(IVector4, X, Y, Z, W) \
    VEC_SWIZZLE_VEC4_FROM_VEC4(IVector4, R, G, B, A) \

#define VEC_SWIZZLE_QUAT_FULL_VEC2 \
    VEC_SWIZZLE_VEC2_FROM_VEC4(Vector2, X, Y, Z, W) \
    
#define VEC_SWIZZLE_QUAT_FULL_VEC3 \
    VEC_SWIZZLE_VEC3_FROM_VEC4(Vector3, X, Y, Z, W) \

#define VEC_SWIZZLE_QUAT_FULL_VEC4 \
    VEC_SWIZZLE_VEC4_FROM_VEC4(Vector4, X, Y, Z, W) \

